### ISSUE TITLE
Version claire

### ISSUE THREAD

**Issue by Thauza** [Orange-Cyberdefense/ocd-mindmaps#1]
Holà,
Est-ce possible de mettre à disposition la version white ? ainsi que la version pdf ?
Pour info, la source xmind n'est pas à jour non plus. Celle-ci diffère des .svg (des pb notamment sur certaines flèches).

**Comment by v1k1ngfr** [comment]
Bonjour,

Nous ne maintenons que la version dark, en svg / png.
La source xmind est à jour dans le répertoire source : https://github.com/Orange-Cyberdefense/ocd-mindmaps/tree/main/src
